resolver: lts-18.21
packages:
  - .
extra-deps:
  - hspec-2.9.4@sha256:658a6a74d5a70c040edd6df2a12228c6d9e63082adaad1ed4d0438ad082a0ef3,1709
  - hspec-core-2.9.4@sha256:a126e9087409fef8dcafcd2f8656456527ac7bb163ed4d9cb3a57589042a5fe8,6498
  - hspec-discover-2.9.4@sha256:fbcf49ecfc3d4da53e797fd0275264cba776ffa324ee223e2a3f4ec2d2c9c4a6,2165

build:
  test-arguments:
    additional-args:
      # See https://hspec.github.io/options.html
      - --times # print duration of each spec item
      - --print-slow-items=3 # print summary of 3 slowest spec items
      # - --format=silent # used to hide normal hspec output to make hooks output more visible
